/**
 * The bundled vocabulary behind generated workspaces: six topics that read like a real team's
 * notes, plus people, dates and general templates. No network, no lorem ipsum.
 *
 * Placeholders in templates: {noun} {noun2} {Noun} {adj} {verb} {proper} {person} {person2}
 * {weekday} {month} {number} {percent} {time}. Titles never contain characters that are unsafe
 * in file names or wikilinks (/ \ : * ? " < > | # ^ [ ]).
 */

export interface Topic {
  id: string;
  label: string;
  icons: readonly string[];
  nouns: readonly string[];
  properNouns: readonly string[];
  adjectives: readonly string[];
  verbs: readonly string[];
  /** Tag names (letters, digits, `-`, `_`, `/` for nesting). */
  tags: readonly string[];
  titles: readonly string[];
  sentences: readonly string[];
  code?: { language: string; snippets: readonly string[] };
}

export const TOPICS: readonly Topic[] = [
  {
    id: 'space',
    label: 'Space exploration',
    icons: ['🚀', '🛰️', '🌙', '🪐', '🔭', '☄️'],
    nouns: [
      'launch window',
      'lunar module',
      'heat shield',
      'telemetry stream',
      'docking port',
      'orbital insertion',
      'guidance computer',
      'ground station',
      'payload fairing',
      'reentry corridor',
      'propellant budget',
      'star tracker',
      'sample return',
      'landing ellipse',
      'mission timeline',
      'crew capsule',
      'solar array',
      'abort mode',
    ],
    properNouns: [
      'Apollo 11',
      'Apollo 13',
      'Voyager 2',
      'Gemini 4',
      'Sputnik',
      'Skylab',
      'Cassini',
      'Hubble',
      'Artemis II',
      'Perseverance',
      'Vostok 1',
      'Mir',
      'Hayabusa2',
      'New Horizons',
    ],
    adjectives: ['orbital', 'lunar', 'crewed', 'robotic', 'suborbital', 'deep-space', 'redundant'],
    verbs: ['launch', 'track', 'dock', 'deorbit', 'calibrate', 'simulate', 'rehearse', 'recover'],
    tags: ['space', 'space/apollo', 'space/probes', 'space/stations', 'history', 'missions'],
    titles: [
      '{proper} mission notes',
      'The {noun} of {proper}',
      'Timeline of {proper}',
      '{Noun} basics',
      'Why the {noun} matters',
      'Lessons from {proper}',
      '{adj} {noun} checklist',
      'Reading notes on {proper}',
      '{proper} and the {noun}',
      'Open questions about the {noun}',
    ],
    sentences: [
      'The {noun} on {proper} was tested three times before the crew signed off.',
      'Engineers rehearsed every {adj} {noun} scenario in the simulator for weeks.',
      '{person} pointed out that the {noun} left almost no margin for the {noun2}.',
      'During {proper}, the {noun} behaved exactly as the models predicted.',
      'We still do not know why the {noun2} drifted after the burn.',
      'A single {noun} failure would have forced an early abort.',
      'The archive has {number} pages of transcripts about the {noun}.',
      'Mission control could {verb} the {noun} only while the ground station had a signal.',
    ],
  },
  {
    id: 'engineering',
    label: 'Engineering',
    icons: ['🛠️', '⚙️', '🧪', '🧩', '📦', '🐛'],
    nouns: [
      'sync server',
      'schema migration',
      'search index',
      'release pipeline',
      'database index',
      'feature flag',
      'error budget',
      'cache layer',
      'job queue',
      'API gateway',
      'test suite',
      'build cache',
      'load balancer',
      'retry policy',
      'bundle size',
      'rate limiter',
      'audit log',
      'staging environment',
    ],
    properNouns: [
      'Postgres',
      'SQLite',
      'Redis',
      'Kubernetes',
      'WebAssembly',
      'GraphQL',
      'Playwright',
      'Vite',
      'TypeScript',
      'Rust',
      'Grafana',
      'Terraform',
    ],
    adjectives: ['flaky', 'idempotent', 'incremental', 'backward-compatible', 'noisy', 'stateless'],
    verbs: ['refactor', 'benchmark', 'profile', 'migrate', 'deploy', 'roll back', 'shard', 'cache'],
    tags: ['engineering', 'eng/backend', 'eng/frontend', 'eng/infra', 'incident', 'rfc', 'perf'],
    titles: [
      'RFC {number} {noun} redesign',
      '{Noun} runbook',
      'Postmortem {month} {noun} outage',
      'Migrating the {noun} to {proper}',
      '{adj} {noun} investigation',
      'Benchmarking the {noun}',
      '{proper} upgrade plan',
      'Design notes for the {noun}',
      'On-call handbook for the {noun}',
      '{Noun} performance budget',
    ],
    sentences: [
      'We should {verb} the {noun} before the {noun2} grows any further.',
      'The {noun} was {adj} for most of {month}, which hid a real bug.',
      '{person} measured a p95 of {number} ms after the change to the {noun}.',
      'Rolling back the {noun} took {number} minutes, mostly waiting for the {noun2}.',
      'Keep the {noun} {adj}; retries must never double-apply a write.',
      'The {proper} dashboard shows the {noun} saturating around {percent} load.',
      'If we {verb} the {noun} first, the {noun2} migration becomes trivial.',
      'Nobody owns the {noun} today, so alerts go to whoever is on call.',
    ],
    code: {
      language: 'typescript',
      snippets: [
        'const results = await index.query(term, { limit: 20 });\nconsole.log(results.hits.length);',
        'export function retry<T>(run: () => Promise<T>, attempts = 3): Promise<T> {\n  return run().catch((error) => (attempts > 1 ? retry(run, attempts - 1) : Promise.reject(error)));\n}',
        "const started = performance.now();\nawait store.flush();\nmetrics.record('flush_ms', performance.now() - started);",
      ],
    },
  },
  {
    id: 'garden',
    label: 'Gardening',
    icons: ['🌱', '🌻', '🍅', '🪴', '🌿', '🥕'],
    nouns: [
      'raised bed',
      'compost pile',
      'tomato seedling',
      'drip line',
      'cover crop',
      'herb spiral',
      'rain barrel',
      'bean trellis',
      'soil test',
      'seed catalog',
      'mulch layer',
      'pollinator strip',
      'cold frame',
      'fruit tree',
    ],
    properNouns: [
      'San Marzano',
      'Cherokee Purple',
      'Brandywine',
      'Genovese basil',
      'Scarlet Runner',
    ],
    adjectives: [
      'perennial',
      'shade-tolerant',
      'frost-hardy',
      'heirloom',
      'drought-proof',
      'organic',
    ],
    verbs: ['sow', 'transplant', 'prune', 'mulch', 'harvest', 'water', 'rotate', 'overwinter'],
    tags: ['garden', 'garden/vegetables', 'garden/herbs', 'seasonal', 'outdoors'],
    titles: [
      '{month} garden plan',
      '{Noun} build log',
      'Growing {proper}',
      '{adj} plants for the {noun}',
      'Seed starting schedule',
      'What worked in the {noun} this year',
      '{Noun} troubleshooting',
      'Harvest log {month}',
    ],
    sentences: [
      'Sow the {proper} indoors six weeks before the last frost.',
      'The {noun} needs a thicker {noun2} before the summer heat.',
      '{person} swears by adding coffee grounds to the {noun}.',
      'We lost {number} seedlings to a cold snap in {month}.',
      'Next year, {verb} the {noun} earlier and keep the {noun2} shaded.',
      'The {adj} varieties did far better along the {noun}.',
    ],
  },
  {
    id: 'kitchen',
    label: 'Cooking',
    icons: ['🍳', '🥖', '🍜', '🧄', '🍋', '🫕'],
    nouns: [
      'sourdough starter',
      'stock pot',
      'spice blend',
      'pickle brine',
      'pie crust',
      'tomato sauce',
      'miso glaze',
      'dough hydration',
      'braising liquid',
      'meal plan',
      'grocery list',
      'knife skill',
    ],
    properNouns: ['Pad Thai', 'Shakshuka', 'Ratatouille', 'Focaccia', 'Dal makhani', 'Bibimbap'],
    adjectives: ['fermented', 'weeknight', 'slow-cooked', 'crispy', 'make-ahead', 'one-pan'],
    verbs: ['braise', 'proof', 'toast', 'reduce', 'season', 'ferment', 'knead', 'simmer'],
    tags: ['recipes', 'recipes/weeknight', 'recipes/baking', 'food', 'meal-prep'],
    titles: [
      '{proper} recipe',
      '{adj} {proper}',
      'Notes on {noun}',
      'Weekly {noun}',
      '{Noun} experiments',
      'Dinner party menu for {month}',
      'Fixing a sluggish {noun}',
    ],
    sentences: [
      '{verb} the onions slowly; the {noun} depends on it.',
      'The {proper} from {weekday} needed more acid and less salt.',
      '{person} doubled the {noun} and it still disappeared in minutes.',
      'Keep the {noun} in the fridge for up to {number} days.',
      'A {adj} version works if you prepare the {noun2} the night before.',
      'Hydration at {percent} made the crumb open and glossy.',
    ],
  },
  {
    id: 'product',
    label: 'Product',
    icons: ['🧭', '📈', '🗺️', '💡', '🎯', '🗂️'],
    nouns: [
      'onboarding flow',
      'pricing page',
      'user interview',
      'roadmap',
      'activation metric',
      'design review',
      'beta program',
      'feature request',
      'churn survey',
      'launch plan',
      'support queue',
      'empty state',
      'command palette',
      'weekly update',
    ],
    properNouns: [
      'Q1 planning',
      'Q2 planning',
      'Q3 planning',
      'Q4 planning',
      'Launch week',
      'Beta cohort',
    ],
    adjectives: [
      'self-serve',
      'first-run',
      'keyboard-first',
      'accessible',
      'mobile',
      'opinionated',
    ],
    verbs: ['prototype', 'interview', 'prioritize', 'ship', 'measure', 'simplify', 'announce'],
    tags: ['product', 'product/research', 'product/launch', 'meeting', 'decision', 'idea'],
    titles: [
      '{proper} notes',
      '{Noun} teardown',
      '{adj} {noun} proposal',
      'Interview with {person}',
      'Weekly sync {month} {number}',
      'Decision log for the {noun}',
      '{Noun} metrics review',
      'Ideas for the {noun}',
      'Retro after {proper}',
    ],
    sentences: [
      '{person} asked whether the {noun} could be {adj} from day one.',
      'Five of {number} users skipped the {noun} entirely.',
      'We decided to {verb} the {noun} before touching the {noun2}.',
      'The {noun} converts at {percent}, well under the target.',
      'Action item: {person2} drafts the {noun} copy by {weekday}.',
      'Support tickets about the {noun} doubled after the last release.',
      'Keep the {noun} {adj}; every extra step costs signups.',
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icons: ['🧳', '🗺️', '🚆', '🏔️', '🏖️', '📸'],
    nouns: [
      'night train',
      'packing list',
      'day hike',
      'ferry route',
      'food market',
      'museum pass',
      'rail pass',
      'city walk',
      'guesthouse',
      'visa appointment',
      'itinerary',
      'photo walk',
    ],
    properNouns: [
      'Lisbon',
      'Kyoto',
      'Oaxaca',
      'Tbilisi',
      'Reykjavik',
      'Marrakesh',
      'Hanoi',
      'Porto',
    ],
    adjectives: ['slow', 'car-free', 'off-season', 'budget', 'scenic', 'rainy-day'],
    verbs: ['book', 'pack', 'explore', 'walk', 'photograph', 'plan', 'map'],
    tags: ['travel', 'travel/europe', 'travel/asia', 'trips', 'bucket-list'],
    titles: [
      '{proper} trip plan',
      '{adj} weekend in {proper}',
      '{Noun} tips',
      '{proper} {noun}',
      'Packing list for {month}',
      'Things to try in {proper}',
    ],
    sentences: [
      'The {noun} in {proper} leaves at {time} and fills up fast.',
      '{person} recommends booking the {noun} at least {number} days ahead.',
      '{adj} plans leave room for the {noun2} nobody mentions in guides.',
      'Skip the {noun} on {weekday}; it closes early.',
      'We walked {number} kilometres on the way to the {noun} and loved every one.',
    ],
  },
];

export const PEOPLE: readonly string[] = [
  'Ada',
  'Amara',
  'Bea',
  'Chen',
  'Dmitri',
  'Emeka',
  'Farah',
  'Grace',
  'Hiro',
  'Ines',
  'Jonas',
  'Kavya',
  'Leila',
  'Mateo',
  'Nadia',
  'Oskar',
  'Priya',
  'Quinn',
  'Rosa',
  'Sven',
  'Tariq',
  'Uma',
  'Valentina',
  'Wei',
  'Yusuf',
  'Zoe',
];

export const SURNAMES: readonly string[] = [
  'Okafor',
  'Lindqvist',
  'Tanaka',
  'Moreau',
  'Haddad',
  'Kowalski',
  'Nakamura',
  'Oliveira',
  'Petrov',
  'Rahman',
  'Schmidt',
  'Vargas',
];

export const WEEKDAYS: readonly string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

export const MONTHS: readonly string[] = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

/** Tags every topic can use. */
export const GENERAL_TAGS: readonly string[] = ['todo', 'draft', 'reference', 'important', 'later'];

/** Section headings inside a page. */
export const HEADINGS: readonly string[] = [
  'Context',
  'Notes',
  'Open questions',
  'Next steps',
  'Decisions',
  'Background',
  'What we learned',
  'Links',
  'Timeline',
  'Summary',
  'Risks',
  'Ideas',
];

export const TASKS: readonly string[] = [
  'Draft the {noun} proposal',
  'Ask {person} about the {noun}',
  'Review the {noun} with {person2}',
  'Set aside time to {verb} the {noun}',
  'Write up what we learned about the {noun}',
  'Compare the {noun} with the {noun2}',
  'Share the {noun} notes with the team',
  'Check the {noun} again on {weekday}',
];

export const CALLOUTS: ReadonlyArray<{
  emoji: string;
  tone: 'info' | 'success' | 'warning' | 'danger' | 'default';
  text: string;
}> = [
  {
    emoji: '💡',
    tone: 'info',
    text: 'Tip: {verb} the {noun} first, then everything else follows.',
  },
  { emoji: '⚠️', tone: 'warning', text: 'Careful: the {noun} changes behaviour after {month}.' },
  { emoji: '✅', tone: 'success', text: 'Decided on {weekday}: we keep the {adj} {noun}.' },
  { emoji: '🚨', tone: 'danger', text: 'Never skip the {noun} check, even under time pressure.' },
  { emoji: '📌', tone: 'default', text: 'Pinned: {person} owns the {noun} until {month}.' },
];

export const QUOTES: readonly string[] = [
  'The best way to predict the future is to invent it.',
  'Plans are worthless, but planning is everything.',
  'Simple things should be simple, complex things should be possible.',
  'Make it work, make it right, make it fast.',
  'Weeks of coding can save you hours of planning.',
  'A garden is a grand teacher.',
];

export const LINK_PHRASES: readonly string[] = [
  'See {link} for the details.',
  'This builds on {link}.',
  'Related: {link}.',
  'Compare with {link}.',
  '{person} summarized this in {link}.',
  'Background is in {link}.',
];

/** Links to external sites used in link marks (never fetched). */
export const EXTERNAL_LINKS: ReadonlyArray<readonly [string, string]> = [
  ['the NASA history archive', 'https://history.nasa.gov/'],
  ['the Yjs docs', 'https://docs.yjs.dev/'],
  ['the RHS plant finder', 'https://www.rhs.org.uk/plants'],
  ['Serious Eats', 'https://www.seriouseats.com/'],
  ['Nielsen Norman Group', 'https://www.nngroup.com/'],
  ['Seat61', 'https://www.seat61.com/'],
];
