import { customAlphabet, nanoid } from 'nanoid';

/** Length of IDs generated by {@link newId}. */
export const ID_LENGTH = 21;

/**
 * Pattern every stored ID must match: URL-, file-name- and doc-name-safe, 1 to 64 characters.
 * Generated IDs are nanoid(21); imported IDs may be shorter or longer, but must match this.
 */
export const ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;

/**
 * Creates a new random ID (nanoid, 21 characters, URL-safe alphabet).
 * Use it for pages, databases, properties, select options, rows, views and workspaces.
 *
 * @example
 * const pageId = newId(); // 'V1StGXR8_Z5jdHi6B-myT'
 */
export function newId(): string {
  return nanoid(ID_LENGTH);
}

/** Returns true when `value` is a string that matches {@link ID_PATTERN}. */
export function isValidId(value: unknown): value is string {
  return typeof value === 'string' && ID_PATTERN.test(value);
}

/**
 * Pattern for block IDs (the `blockId` attribute of block nodes). Compatible with Obsidian
 * block references (`^my-block`): letters, digits and dashes, 1 to 64 characters.
 */
export const BLOCK_ID_PATTERN = /^[A-Za-z0-9-]{1,64}$/;

const blockIdAlphabet = customAlphabet('0123456789abcdefghijklmnopqrstuvwxyz', 8);

/**
 * Creates a short block ID (8 lowercase alphanumerics). Pass the IDs already used in the
 * document to guarantee uniqueness within it.
 *
 * @example
 * const blockId = newBlockId(new Set(['a1b2c3d4']));
 */
export function newBlockId(existing?: ReadonlySet<string>): string {
  for (;;) {
    const id = blockIdAlphabet();
    if (!existing?.has(id)) return id;
  }
}

/** Returns true when `value` is a valid block ID. */
export function isValidBlockId(value: unknown): value is string {
  return typeof value === 'string' && BLOCK_ID_PATTERN.test(value);
}
