/** Realistic data for the databases specs and screenshots: a reading list. */
export interface Book {
  title: string;
  author: string;
  pages: number;
  status: 'Finished' | 'Reading' | 'To read';
  genres: string;
  finished: string;
  owned: boolean;
  link: string;
  contact: string;
}

export const BOOKS: readonly Book[] = [
  {
    title: 'Dune',
    author: 'Frank Herbert',
    pages: 688,
    status: 'Finished',
    genres: 'Science fiction, Classic',
    finished: '2026-01-14',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Dune_(novel)',
    contact: 'club@example.org',
  },
  {
    title: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    pages: 304,
    status: 'Finished',
    genres: 'Science fiction',
    finished: '2026-02-02',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Left_Hand_of_Darkness',
    contact: 'club@example.org',
  },
  {
    title: 'Piranesi',
    author: 'Susanna Clarke',
    pages: 272,
    status: 'Finished',
    genres: 'Fantasy',
    finished: '2026-02-20',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/Piranesi_(novel)',
    contact: 'library@example.org',
  },
  {
    title: 'The Overstory',
    author: 'Richard Powers',
    pages: 512,
    status: 'Reading',
    genres: 'Literary, Nature',
    finished: '',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Overstory',
    contact: 'club@example.org',
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    pages: 496,
    status: 'Finished',
    genres: 'Science fiction',
    finished: '2026-03-08',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Project_Hail_Mary',
    contact: 'club@example.org',
  },
  {
    title: 'Middlemarch',
    author: 'George Eliot',
    pages: 880,
    status: 'To read',
    genres: 'Classic, Literary',
    finished: '',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/Middlemarch',
    contact: 'library@example.org',
  },
  {
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    pages: 320,
    status: 'Finished',
    genres: 'Literary, Science fiction',
    finished: '2026-03-29',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Klara_and_the_Sun',
    contact: 'club@example.org',
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    pages: 662,
    status: 'Reading',
    genres: 'Fantasy',
    finished: '',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Name_of_the_Wind',
    contact: 'club@example.org',
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    pages: 443,
    status: 'Finished',
    genres: 'History, Nonfiction',
    finished: '2026-04-15',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/Sapiens:_A_Brief_History_of_Humankind',
    contact: 'library@example.org',
  },
  {
    title: 'Braiding Sweetgrass',
    author: 'Robin Wall Kimmerer',
    pages: 408,
    status: 'To read',
    genres: 'Nature, Nonfiction',
    finished: '',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Braiding_Sweetgrass',
    contact: 'club@example.org',
  },
  {
    title: 'The Dispossessed',
    author: 'Ursula K. Le Guin',
    pages: 387,
    status: 'Finished',
    genres: 'Science fiction, Classic',
    finished: '2026-05-03',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Dispossessed',
    contact: 'club@example.org',
  },
  {
    title: 'Circe',
    author: 'Madeline Miller',
    pages: 393,
    status: 'Finished',
    genres: 'Fantasy, Myth',
    finished: '2026-05-21',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/Circe_(novel)',
    contact: 'library@example.org',
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    pages: 499,
    status: 'To read',
    genres: 'Psychology, Nonfiction',
    finished: '',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow',
    contact: 'club@example.org',
  },
  {
    title: 'The Three-Body Problem',
    author: 'Liu Cixin',
    pages: 400,
    status: 'Finished',
    genres: 'Science fiction',
    finished: '2026-06-11',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Three-Body_Problem_(novel)',
    contact: 'club@example.org',
  },
  {
    title: 'A Memory Called Empire',
    author: 'Arkady Martine',
    pages: 462,
    status: 'Reading',
    genres: 'Science fiction',
    finished: '',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/A_Memory_Called_Empire',
    contact: 'library@example.org',
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    pages: 334,
    status: 'Finished',
    genres: 'Memoir, Nonfiction',
    finished: '2026-07-02',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Educated_(memoir)',
    contact: 'club@example.org',
  },
  {
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    pages: 310,
    status: 'Finished',
    genres: 'Fantasy, Classic',
    finished: '2026-07-19',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Hobbit',
    contact: 'club@example.org',
  },
  {
    title: 'Station Eleven',
    author: 'Emily St. John Mandel',
    pages: 333,
    status: 'To read',
    genres: 'Literary, Science fiction',
    finished: '',
    owned: false,
    link: 'https://en.wikipedia.org/wiki/Station_Eleven',
    contact: 'library@example.org',
  },
  {
    title: 'The Book of Tea',
    author: 'Kakuzō Okakura',
    pages: 160,
    status: 'Finished',
    genres: 'Classic, Nonfiction',
    finished: '2026-08-08',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/The_Book_of_Tea',
    contact: 'club@example.org',
  },
  {
    title: 'Children of Time',
    author: 'Adrian Tchaikovsky',
    pages: 600,
    status: 'Reading',
    genres: 'Science fiction',
    finished: '',
    owned: true,
    link: 'https://en.wikipedia.org/wiki/Children_of_Time_(novel)',
    contact: 'club@example.org',
  },
];
